export const handle = {
  top: {
    marginTop: -4,
    marginLeft: -5,
    top: 0,
    left: "50%",
    cursor: "ns-resize",
    border: "3px solid #999",
    borderLeft: "none",
    borderRight: "none",
    borderBottom: "none",
    borderWidth: 5,
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  topLeft: {
    marginTop: -4,
    marginLeft: -4,
    top: 0,
    left: 0,
    cursor: "nwse-resize",
    border: "3px solid #999",
    borderRight: "none",
    borderBottom: "none",
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  left: {
    marginTop: -5,
    marginLeft: -4,
    top: "50%",
    left: 0,
    cursor: "ew-resize",
    border: "3px solid #999",
    borderTop: "none",
    borderRight: "none",
    borderBottom: "none",
    borderWidth: 5,
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  bottomLeft: {
    marginTop: -16,
    marginLeft: -4,
    top: "100%",
    left: 0,
    cursor: "nesw-resize",
    border: "3px solid #999",
    borderRight: "none",
    borderTop: "none",
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  bottom: {
    marginTop: -15,
    marginLeft: -5,
    top: "100%",
    left: "50%",
    cursor: "ns-resize",
    border: "3px solid #999",
    borderLeft: "none",
    borderRight: "none",
    borderTop: "none",
    borderWidth: 5,
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  bottomRight: {
    marginTop: -16,
    marginLeft: -16,
    top: "100%",
    left: "100%",
    cursor: "nwse-resize",
    border: "3px solid #999",
    borderLeft: "none",
    borderTop: "none",
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  right: {
    marginTop: -5,
    marginLeft: -15,
    top: "50%",
    left: "100%",
    cursor: "ew-resize",
    border: "3px solid #999",
    borderTop: "none",
    borderLeft: "none",
    borderBottom: "none",
    borderWidth: 5,
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
  topRight: {
    marginTop: -3,
    marginLeft: -17,
    top: 0,
    left: "100%",
    cursor: "nesw-resize",
    border: "3px solid #999",
    borderLeft: "none",
    borderBottom: "none",
    borderColor: "#09f",
    width: 20,
    height: 20,
    boxSizing: "border-box",
    zIndex: 1,
  },
};
